---
- name: test ping
  hosts: wordpress
  tasks:
  - name: ping
    ping:

  - name: Install PHP
    package: 
      name: "{{ item }}"
      state: present
    loop:
      - php
      - php-fpm
      - php-mysql
      - php-xml

  - name: Remove apache2
    package:
      name: apache2
      state: absent
...